fix: if the backup fails return a failure code

diff --git a/apps/base/tayle/db-backup-job.yaml b/apps/base/tayle/db-backup-job.yaml
--- a/apps/base/tayle/db-backup-job.yaml
+++ b/apps/base/tayle/db-backup-job.yaml
@@ -19,6 +19,10 @@ spec:
                 - |
                   echo "Starting database backup..."
                   pg_dump -v -h db -U $POSTGRES_USER -d $POSTGRES_DB -Fc > /backup/db-$(date +%Y%m%d-%H%M%S).dump
+                  if [ $? -ne 0 ]; then
+                    echo "Backup failed"
+                    exit 1
+                  fi
                   echo "Backup completed. Starting cleanup process..."
 
                   cd /backup
